pub mod state;
pub mod spread;
pub mod normalizer;
pub mod price_feed;
pub mod circuit_breaker;
pub mod trading_strategy;
pub mod position_manager;
pub mod trading_history;
pub mod ring_buffer;
pub mod capital_manager;
pub mod time_sync;
pub mod price_matcher;
pub mod price_synchronizer;
pub mod arbitrage_decision;

pub use state::PriceState;
pub use price_feed::PriceFeedManager;
pub use circuit_breaker::CircuitBreaker;
pub use trading_strategy::Position;
pub use position_manager::PositionManager;
pub use trading_history::{TradingStats, TradeRecord};
pub use time_sync::TimeSync;
pub use ring_buffer::{RingBuffer, PriceSnapshot};
